module.exports = {
  up(knex, Promise) {
    return knex.raw('CREATE TABLE suits (suitid int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, suitname text)');

    /*return knex.schema.createTable('suits', (table) => {
      table.increments('id').primary();
      table.text('suitname');
    });
    */
  },
  down(knex, Promise) {
    return knex.schema.dropTable('suits');
  }
}
